export const products = [
  {
    id: 1,
    name: "Wireless Noise-Cancelling Headphones",
    slug: "wireless-noise-cancelling-headphones",
    price: 299.99,
    originalPrice: 399.99,
    discount: 25,
    rating: 4.8,
    reviews: 2341,
    image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=400&h=400&fit=crop",
    category: "Electronics",
    brand: "SoundMax",
    stock: 45,
    description: "Premium wireless headphones with active noise cancellation, 30-hour battery life, and ultra-comfortable over-ear design.",
    seller: "TechZone Official",
    tags: ["trending", "flash-sale"],
  },
  {
    id: 2,
    name: "Smart Fitness Watch Pro",
    slug: "smart-fitness-watch-pro",
    price: 199.99,
    originalPrice: 249.99,
    discount: 20,
    rating: 4.6,
    reviews: 1892,
    image: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=400&h=400&fit=crop",
    category: "Electronics",
    brand: "FitTech",
    stock: 120,
    description: "Advanced fitness tracking with GPS, heart rate monitoring, sleep analysis, and 7-day battery life.",
    seller: "FitTech Store",
    tags: ["trending", "recommended"],
  },
  {
    id: 3,
    name: "Premium Leather Backpack",
    slug: "premium-leather-backpack",
    price: 89.99,
    originalPrice: 129.99,
    discount: 31,
    rating: 4.7,
    reviews: 956,
    image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=400&h=400&fit=crop",
    category: "Fashion",
    brand: "UrbanEdge",
    stock: 78,
    description: "Handcrafted genuine leather backpack with laptop compartment, multiple pockets, and water-resistant coating.",
    seller: "UrbanEdge Fashion",
    tags: ["trending", "flash-sale"],
  },
  {
    id: 4,
    name: "Organic Skincare Set",
    slug: "organic-skincare-set",
    price: 59.99,
    originalPrice: 79.99,
    discount: 25,
    rating: 4.9,
    reviews: 3210,
    image: "https://images.unsplash.com/photo-1556228578-0d85b1a4d571?w=400&h=400&fit=crop",
    category: "Beauty",
    brand: "NaturGlow",
    stock: 200,
    description: "Complete organic skincare routine with cleanser, toner, serum, and moisturizer. Suitable for all skin types.",
    seller: "NaturGlow Official",
    tags: ["recommended", "flash-sale"],
  },
  {
    id: 5,
    name: "Minimalist Desk Lamp",
    slug: "minimalist-desk-lamp",
    price: 45.99,
    originalPrice: 59.99,
    discount: 23,
    rating: 4.5,
    reviews: 678,
    image: "https://images.unsplash.com/photo-1507473885765-e6ed057ab854?w=400&h=400&fit=crop",
    category: "Home",
    brand: "LumiDesign",
    stock: 150,
    description: "Modern LED desk lamp with adjustable brightness, color temperature control, and wireless charging base.",
    seller: "LumiDesign Home",
    tags: ["recommended"],
  },
  {
    id: 6,
    name: "Running Shoes Ultra Boost",
    slug: "running-shoes-ultra-boost",
    price: 149.99,
    originalPrice: 189.99,
    discount: 21,
    rating: 4.7,
    reviews: 4521,
    image: "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=400&h=400&fit=crop",
    category: "Sports",
    brand: "SprintX",
    stock: 90,
    description: "Lightweight running shoes with responsive cushioning, breathable mesh upper, and durable rubber outsole.",
    seller: "SprintX Athletics",
    tags: ["trending", "flash-sale"],
  },
  {
    id: 7,
    name: "Portable Bluetooth Speaker",
    slug: "portable-bluetooth-speaker",
    price: 79.99,
    originalPrice: 99.99,
    discount: 20,
    rating: 4.4,
    reviews: 1245,
    image: "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=400&h=400&fit=crop",
    category: "Electronics",
    brand: "BassWave",
    stock: 65,
    description: "Waterproof Bluetooth speaker with 360-degree sound, 20-hour playtime, and built-in microphone.",
    seller: "BassWave Audio",
    tags: ["recommended"],
  },
  {
    id: 8,
    name: "Ceramic Coffee Mug Set",
    slug: "ceramic-coffee-mug-set",
    price: 34.99,
    originalPrice: 44.99,
    discount: 22,
    rating: 4.6,
    reviews: 890,
    image: "https://images.unsplash.com/photo-1514228742587-6b1558fcca3d?w=400&h=400&fit=crop",
    category: "Home",
    brand: "CraftHouse",
    stock: 300,
    description: "Set of 4 handmade ceramic mugs with unique glazed finish. Microwave and dishwasher safe.",
    seller: "CraftHouse Living",
    tags: ["flash-sale"],
  },
  {
    id: 9,
    name: "Yoga Mat Premium",
    slug: "yoga-mat-premium",
    price: 39.99,
    originalPrice: 54.99,
    discount: 27,
    rating: 4.8,
    reviews: 2100,
    image: "https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=400&h=400&fit=crop",
    category: "Sports",
    brand: "ZenFit",
    stock: 175,
    description: "Extra-thick eco-friendly yoga mat with non-slip surface, alignment lines, and carrying strap.",
    seller: "ZenFit Wellness",
    tags: ["trending", "recommended"],
  },
  {
    id: 10,
    name: "Designer Sunglasses",
    slug: "designer-sunglasses",
    price: 129.99,
    originalPrice: 179.99,
    discount: 28,
    rating: 4.5,
    reviews: 1567,
    image: "https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=400&h=400&fit=crop",
    category: "Fashion",
    brand: "VisionLux",
    stock: 55,
    description: "Polarized UV400 sunglasses with titanium frame and scratch-resistant lenses.",
    seller: "VisionLux Eyewear",
    tags: ["trending"],
  },
  {
    id: 11,
    name: "Mechanical Gaming Keyboard",
    slug: "mechanical-gaming-keyboard",
    price: 119.99,
    originalPrice: 159.99,
    discount: 25,
    rating: 4.7,
    reviews: 3456,
    image: "https://images.unsplash.com/photo-1541140532154-b024d705b90a?w=400&h=400&fit=crop",
    category: "Electronics",
    brand: "KeyForce",
    stock: 40,
    description: "RGB mechanical keyboard with hot-swappable switches, aluminum frame, and programmable macros.",
    seller: "KeyForce Gaming",
    tags: ["flash-sale", "trending"],
  },
  {
    id: 12,
    name: "Aromatherapy Diffuser",
    slug: "aromatherapy-diffuser",
    price: 29.99,
    originalPrice: 39.99,
    discount: 25,
    rating: 4.3,
    reviews: 1123,
    image: "https://images.unsplash.com/photo-1602928321679-560bb453f190?w=400&h=400&fit=crop",
    category: "Home",
    brand: "AromaZen",
    stock: 220,
    description: "Ultrasonic essential oil diffuser with LED mood lighting and auto shut-off timer.",
    seller: "AromaZen Lifestyle",
    tags: ["recommended"],
  },
]

export const categories = [
  { id: 1, name: "Electronics", icon: "Monitor", count: 1240, slug: "electronics" },
  { id: 2, name: "Fashion", icon: "Shirt", count: 3450, slug: "fashion" },
  { id: 3, name: "Beauty", icon: "Sparkles", count: 890, slug: "beauty" },
  { id: 4, name: "Home", icon: "Home", count: 2100, slug: "home" },
  { id: 5, name: "Sports", icon: "Dumbbell", count: 1567, slug: "sports" },
  { id: 6, name: "Books", icon: "BookOpen", count: 4200, slug: "books" },
  { id: 7, name: "Toys", icon: "Gamepad2", count: 780, slug: "toys" },
  { id: 8, name: "Grocery", icon: "ShoppingBasket", count: 5600, slug: "grocery" },
]

export const sellers = [
  { id: 1, name: "TechZone Official", rating: 4.9, products: 256, image: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?w=100&h=100&fit=crop" },
  { id: 2, name: "FitTech Store", rating: 4.8, products: 189, image: "https://images.unsplash.com/photo-1472851294608-062f824d29cc?w=100&h=100&fit=crop" },
  { id: 3, name: "UrbanEdge Fashion", rating: 4.7, products: 342, image: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=100&h=100&fit=crop" },
  { id: 4, name: "NaturGlow Official", rating: 4.9, products: 128, image: "https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?w=100&h=100&fit=crop" },
]

export const banners = [
  {
    id: 1,
    title: "Mega Sale is Live",
    subtitle: "Up to 70% off on Electronics",
    cta: "Shop Now",
    bg: "from-primary to-primary/80",
  },
  {
    id: 2,
    title: "New Arrivals",
    subtitle: "Fresh styles for the new season",
    cta: "Explore",
    bg: "from-accent to-accent/80",
  },
  {
    id: 3,
    title: "Free Shipping",
    subtitle: "On orders over $50",
    cta: "Learn More",
    bg: "from-chart-3 to-chart-3/80",
  },
]

export const orders = [
  { id: "ORD-2024001", date: "2026-02-20", status: "Delivered", total: 299.99, items: 2 },
  { id: "ORD-2024002", date: "2026-02-18", status: "Shipped", total: 149.99, items: 1 },
  { id: "ORD-2024003", date: "2026-02-15", status: "Processing", total: 89.99, items: 3 },
  { id: "ORD-2024004", date: "2026-02-10", status: "Delivered", total: 459.97, items: 4 },
  { id: "ORD-2024005", date: "2026-02-05", status: "Cancelled", total: 34.99, items: 1 },
]

export const adminStats = {
  totalRevenue: 124589.99,
  totalOrders: 3421,
  totalUsers: 12456,
  totalProducts: 8934,
  revenueData: [
    { month: "Jan", revenue: 12400 },
    { month: "Feb", revenue: 15600 },
    { month: "Mar", revenue: 18200 },
    { month: "Apr", revenue: 14800 },
    { month: "May", revenue: 21000 },
    { month: "Jun", revenue: 19500 },
    { month: "Jul", revenue: 23100 },
  ],
  ordersByStatus: [
    { name: "Delivered", value: 2100 },
    { name: "Shipped", value: 650 },
    { name: "Processing", value: 421 },
    { name: "Cancelled", value: 250 },
  ],
}
